// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class LocalizationTestsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testFeature3() {
    driver.get("http://localhost:8080/administrator/");
    driver.manage().window().setSize(new Dimension(1280, 720));
    System.out.println("{ASSESSOR}:LoginPage:adminLogin");
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("admin@prestashop.com");
    driver.findElement(By.id("passwd")).click();
    driver.findElement(By.id("passwd")).sendKeys("password");
    driver.findElement(By.name("submitLogin")).click();
    System.out.println("{ASSESSOR}:DashboardPage:ClickLocalization");
    {
      WebElement element = driver.findElement(By.cssSelector("#maintab-AdminParentLocalization span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("States")).click();
    System.out.println("{ASSESSOR}:StatesPage:addState");
    driver.findElement(By.id("page-header-desc-state-new_state")).click();
    System.out.println("{ASSESSOR}:AddNewStatePage:addDetails");
    driver.findElement(By.id("name")).click();
    driver.findElement(By.id("name")).sendKeys("Liguria");
    driver.findElement(By.id("iso_code")).click();
    driver.findElement(By.id("iso_code")).sendKeys("1121");
    driver.findElement(By.id("id_country")).click();
    driver.findElement(By.cssSelector("#id_country > option:nth-child(4)")).click();
    driver.findElement(By.id("id_zone")).click();
    {
      WebElement dropdown = driver.findElement(By.id("id_zone"));
      dropdown.findElement(By.xpath("//option[. = 'Europe']")).click();
    }
    driver.findElement(By.cssSelector("#id_zone > option:nth-child(4)")).click();
    driver.findElement(By.cssSelector(".process-icon-save")).click();
    System.out.println("{ASSESSOR}:StatesPage:verifyStatesAdditionSuccess");
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".alert-success:nth-child(1)"));
      assert(elements.size() > 0);
    }
    System.out.println("{ASSESSOR}:ProductsPage:logOut");
    driver.findElement(By.cssSelector(".employee_name > .string-long")).click();
    driver.findElement(By.id("header_logout")).click();
  }
  @Test
  public void testFeature4() {
    driver.get("http://localhost:8080/administrator/");
    driver.manage().window().setSize(new Dimension(1280, 720));
    System.out.println("{ASSESSOR}:LoginPage:adminLogin");
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("admin@prestashop.com");
    driver.findElement(By.id("passwd")).click();
    driver.findElement(By.id("passwd")).sendKeys("password");
    driver.findElement(By.name("submitLogin")).click();
    System.out.println("{ASSESSOR}:DashboardPage:ClickLocalization");
    {
      WebElement element = driver.findElement(By.cssSelector("#maintab-AdminParentLocalization span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("States")).click();
    System.out.println("{ASSESSOR}:StatesPage:addState");
    driver.findElement(By.id("page-header-desc-state-new_state")).click();
    driver.findElement(By.cssSelector(".process-icon-save")).click();
    System.out.println("{ASSESSOR}:AddNewStatePage:verifyRedBox");
    assertThat(driver.findElement(By.cssSelector("ol > li:nth-child(1)")).getText(), is("The iso_code field is required."));
    assertThat(driver.findElement(By.cssSelector("ol > li:nth-child(2)")).getText(), is("The name field is required."));
    System.out.println("{ASSESSOR}:ProductsPage:logOut");
    driver.findElement(By.cssSelector(".employee_name > .string-long")).click();
    driver.findElement(By.id("header_logout")).click();
  }
}
