// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ProductTestsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testFeature0() {
    driver.get("http://localhost:8080/administrator/");
    driver.manage().window().setSize(new Dimension(1280, 720));
    System.out.println("{ASSESSOR}:LoginPage:adminLogin");
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("admin@prestashop.com");
    driver.findElement(By.id("passwd")).click();
    driver.findElement(By.id("passwd")).sendKeys("password");
    driver.findElement(By.name("submitLogin")).click();
    System.out.println("{ASSESSOR}:DashboardPage:ClickCatalog");
    {
      WebElement element = driver.findElement(By.cssSelector("#maintab-AdminCatalog span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    System.out.println("{ASSESSOR}:DashboardPage:ClickProducts");
    driver.findElement(By.linkText("Products")).click();
    System.out.println("{ASSESSOR}:ProductsPage:addProduct");
    driver.findElement(By.id("page-header-desc-product-new_product")).click();
    js.executeScript("window.scrollTo(0,0)");
    System.out.println("{ASSESSOR}:AddProductPage:setProductName");
    driver.findElement(By.id("name_1")).click();
    driver.findElement(By.id("name_1")).sendKeys("Blue Jacket3");
    driver.findElement(By.cssSelector(".panel-footer:nth-child(22) > .btn:nth-child(2) > .process-icon-save")).click();
    System.out.println("{ASSESSOR}:ProductsPage:verifyAddingProductSuccessfully");
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".alert-success:nth-child(1)"));
      assert(elements.size() > 0);
    }
    System.out.println("{ASSESSOR}:ProductsPage:logOut");
    driver.findElement(By.cssSelector(".employee_name > .string-long")).click();
    driver.findElement(By.id("header_logout")).click();
  }
  @Test
  public void testFeature1() {
    driver.get("http://localhost:8080/administrator/");
    driver.manage().window().setSize(new Dimension(1280, 720));
    System.out.println("{ASSESSOR}:LoginPage:adminLogin");
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("admin@prestashop.com");
    driver.findElement(By.id("passwd")).click();
    driver.findElement(By.id("passwd")).sendKeys("password");
    driver.findElement(By.name("submitLogin")).click();
    System.out.println("{ASSESSOR}:DashboardPage:ClickCatalog");
    {
      WebElement element = driver.findElement(By.cssSelector("#maintab-AdminCatalog span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    System.out.println("{ASSESSOR}:DashboardPage:ClickProducts");
    driver.findElement(By.linkText("Products")).click();
    System.out.println("{ASSESSOR}:ProductsPage:addProduct");
    driver.findElement(By.id("page-header-desc-product-new_product")).click();
    driver.findElement(By.cssSelector(".panel-footer:nth-child(22) > .btn:nth-child(2) > .process-icon-save")).click();
    System.out.println("{ASSESSOR}:ProductsPage:verifyRedBox");
    assertThat(driver.findElement(By.cssSelector("ol > li:nth-child(1)")).getText(), is("This link_rewrite field is required at least in English (English)"));
    assertThat(driver.findElement(By.cssSelector("ol > li:nth-child(2)")).getText(), is("This name field is required at least in English (English)"));
    System.out.println("{ASSESSOR}:ProductsPage:logOut");
    driver.findElement(By.cssSelector(".employee_name > .string-long")).click();
    driver.findElement(By.id("header_logout")).click();
  }
  @Test
  public void testFeature2() {
    driver.get("http://localhost:8080/administrator/");
    driver.manage().window().setSize(new Dimension(1280, 720));
    System.out.println("{ASSESSOR}:LoginPage:adminLogin");
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("admin@prestashop.com");
    driver.findElement(By.id("passwd")).click();
    driver.findElement(By.id("passwd")).sendKeys("password");
    driver.findElement(By.name("submitLogin")).click();
    System.out.println("{ASSESSOR}:DashboardPage:ClickCatalog");
    {
      WebElement element = driver.findElement(By.cssSelector("#maintab-AdminCatalog span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    System.out.println("{ASSESSOR}:DashboardPage:ClickProducts");
    driver.findElement(By.linkText("Products")).click();
    driver.findElement(By.cssSelector("#tr__8_0 .edit")).click();
    System.out.println("{ASSESSOR}:EditProductPage:changeProductName");
    driver.findElement(By.id("name_1")).click();
    driver.findElement(By.id("name_1")).sendKeys("Deep Blue Jacket");
    js.executeScript("window.scrollTo(0,835)");
    driver.findElement(By.cssSelector(".panel-footer:nth-child(22) > .btn:nth-child(2) > .process-icon-save")).click();
    System.out.println("{ASSESSOR}:ProductsPage:verifyChangeSuccess");
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".alert-success:nth-child(1)"));
      assert(elements.size() > 0);
    }
    System.out.println("{ASSESSOR}:ProductsPage:logOut");
    driver.findElement(By.cssSelector(".employee_name > .string-long")).click();
    driver.findElement(By.id("header_logout")).click();
  }
  @Test
  public void testFeature5() {
    driver.get("http://localhost:8080/administrator/");
    driver.manage().window().setSize(new Dimension(1280, 720));
    System.out.println("{ASSESSOR}:LoginPage:adminLogin");
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("admin@prestashop.com");
    driver.findElement(By.id("passwd")).click();
    driver.findElement(By.id("passwd")).sendKeys("password");
    driver.findElement(By.name("submitLogin")).click();
    System.out.println("{ASSESSOR}:DashboardPage:ClickCatalog");
    {
      WebElement element = driver.findElement(By.cssSelector("#maintab-AdminCatalog span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    System.out.println("{ASSESSOR}:DashboardPage:ClickProducts");
    driver.findElement(By.linkText("Products")).click();
    System.out.println("{ASSESSOR}:ProductsPage:addProduct");
    driver.findElement(By.id("page-header-desc-product-new_product")).click();
    System.out.println("{ASSESSOR}:AddNewStatePage:selectPrices");
    driver.findElement(By.id("link-Prices")).click();
    System.out.println("{ASSESSOR}:AddProductPage:setPreTaxRetailPrice");
    driver.findElement(By.id("priceTE")).click();
    driver.findElement(By.id("priceTE")).sendKeys("10");
    System.out.println("{ASSESSOR}:AddProductPage:checkRetailPriceWithTax");
    driver.findElement(By.id("priceTI")).click();
    {
      String value = driver.findElement(By.id("priceTI")).getAttribute("value");
      assertThat(value, is("12.20"));
    }
    System.out.println("{ASSESSOR}:ProductsPage:logOut");
    driver.findElement(By.cssSelector(".employee_name > .string-long")).click();
    driver.findElement(By.id("header_logout")).click();
  }
  @Test
  public void testFeature6() {
    driver.get("http://localhost:8080/administrator/");
    driver.manage().window().setSize(new Dimension(1280, 720));
    System.out.println("{ASSESSOR}:LoginPage:adminLogin");
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("admin@prestashop.com");
    driver.findElement(By.id("passwd")).click();
    driver.findElement(By.id("passwd")).sendKeys("password");
    driver.findElement(By.name("submitLogin")).click();
    System.out.println("{ASSESSOR}:DashboardPage:ClickCatalog");
    {
      WebElement element = driver.findElement(By.cssSelector("#maintab-AdminCatalog span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    System.out.println("{ASSESSOR}:DashboardPage:ClickProducts");
    driver.findElement(By.linkText("Products")).click();
    System.out.println("{ASSESSOR}:ProductsPage:addProduct");
    driver.findElement(By.id("page-header-desc-product-new_product")).click();
    System.out.println("{ASSESSOR}:AddNewStatePage:selectPrices");
    driver.findElement(By.id("link-Prices")).click();
    System.out.println("{ASSESSOR}:AddProductPage:setPreTaxRetailPrice");
    driver.findElement(By.id("priceTE")).click();
    driver.findElement(By.id("priceTE")).sendKeys("10");
    System.out.println("{ASSESSOR}:AddProductPage:setITReducedRate");
    driver.findElement(By.id("id_tax_rules_group")).click();
    {
      WebElement dropdown = driver.findElement(By.id("id_tax_rules_group"));
      dropdown.findElement(By.xpath("//option[. = 'IT Reduced Rate (10%)']")).click();
    }
    System.out.println("{ASSESSOR}:AddProductPage:checkReducedRetailPriceWithTax");
    {
      String value = driver.findElement(By.id("priceTI")).getAttribute("value");
      assertThat(value, is("11.00"));
    }
    System.out.println("{ASSESSOR}:ProductsPage:logOut");
    driver.findElement(By.cssSelector(".employee_name > .string-long")).click();
    driver.findElement(By.id("header_logout")).click();
  }
  @Test
  public void testFeature7() {
    driver.get("http://localhost:8080/administrator/");
    driver.manage().window().setSize(new Dimension(1280, 720));
    System.out.println("{ASSESSOR}:LoginPage:adminLogin");
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("admin@prestashop.com");
    driver.findElement(By.id("passwd")).click();
    driver.findElement(By.id("passwd")).sendKeys("password");
    driver.findElement(By.name("submitLogin")).click();
    System.out.println("{ASSESSOR}:DashboardPage:ClickCatalog");
    {
      WebElement element = driver.findElement(By.cssSelector("#maintab-AdminCatalog span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    System.out.println("{ASSESSOR}:DashboardPage:ClickProductFeatures");
    driver.findElement(By.linkText("Product Features")).click();
    System.out.println("{ASSESSOR}:ProductFeaturesPage:addFeature");
    driver.findElement(By.cssSelector("#page-header-desc-feature-new_feature > .process-icon-new")).click();
    System.out.println("{ASSESSOR}:AddNewFeaturePage:setFeatureName");
    driver.findElement(By.id("name_1")).click();
    driver.findElement(By.id("name_1")).sendKeys("Strong");
    driver.findElement(By.cssSelector(".process-icon-save")).click();
    System.out.println("{ASSESSOR}:ProductFeaturesPage:verifySuccessfulCreation");
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".alert-success:nth-child(1)"));
      assert(elements.size() > 0);
    }
    System.out.println("{ASSESSOR}:ProductsFeaturesPage:logOut");
    driver.findElement(By.cssSelector(".employee_name > .string-long")).click();
    driver.findElement(By.id("header_logout")).click();
  }
  @Test
  public void testFeature8() {
    driver.get("http://localhost:8080/administrator/");
    driver.manage().window().setSize(new Dimension(1280, 720));
    System.out.println("{ASSESSOR}:LoginPage:adminLogin");
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("admin@prestashop.com");
    driver.findElement(By.id("passwd")).click();
    driver.findElement(By.id("passwd")).sendKeys("password");
    driver.findElement(By.name("submitLogin")).click();
    System.out.println("{ASSESSOR}:DashboardPage:ClickCatalog");
    {
      WebElement element = driver.findElement(By.cssSelector("#maintab-AdminCatalog span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    System.out.println("{ASSESSOR}:DashboardPage:ClickProductFeatures");
    driver.findElement(By.linkText("Product Features")).click();
    System.out.println("{ASSESSOR}:ProductFeaturesPage:addFeature");
    driver.findElement(By.cssSelector("#page-header-desc-feature-new_feature > .process-icon-new")).click();
    driver.findElement(By.cssSelector(".process-icon-save")).click();
    System.out.println("{ASSESSOR}:ProductFeaturesPage:checkRedBox");
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".alert-danger"));
      assert(elements.size() > 0);
    }
    System.out.println("{ASSESSOR}:ProductFeaturesPage:logOut");
    driver.findElement(By.cssSelector(".employee_name > .string-long")).click();
    driver.findElement(By.id("header_logout")).click();
  }
  @Test
  public void testFeature9() {
    driver.get("http://localhost:8080/administrator/");
    driver.manage().window().setSize(new Dimension(1280, 720));
    System.out.println("{ASSESSOR}:LoginPage:adminLogin");
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("admin@prestashop.com");
    driver.findElement(By.id("passwd")).click();
    driver.findElement(By.id("passwd")).sendKeys("password");
    driver.findElement(By.name("submitLogin")).click();
    System.out.println("{ASSESSOR}:DashboardPage:ClickCatalog");
    {
      WebElement element = driver.findElement(By.cssSelector("#maintab-AdminCatalog span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    System.out.println("{ASSESSOR}:DashboardPage:ClickProductAttributes");
    driver.findElement(By.linkText("Product Attributes")).click();
    System.out.println("{ASSESSOR}:ProductAttributesPage:addNewAttribute");
    driver.findElement(By.id("page-header-desc-attribute_group-new_attribute_group")).click();
    System.out.println("{ASSESSOR}:AddNewAttributePage:addAttributeDetails");
    driver.findElement(By.id("name_1")).click();
    driver.findElement(By.id("name_1")).sendKeys("Quantity");
    driver.findElement(By.id("public_name_1")).click();
    driver.findElement(By.id("public_name_1")).sendKeys("Qnt");
    driver.findElement(By.cssSelector(".process-icon-save")).click();
    System.out.println("{ASSESSOR}:ProductAttributesPage:verifySuccessfulCreation");
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".alert-success:nth-child(1)"));
      assert(elements.size() > 0);
    }
    System.out.println("{ASSESSOR}:ProductsPage:logOut");
    driver.findElement(By.cssSelector(".employee_name > .string-long")).click();
    driver.findElement(By.id("header_logout")).click();
  }
}
