package TestCases;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.FixMethodOrder;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;
import TestCases.PO.*;
import org.junit.runners.MethodSorters;

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class LocalizationTestCases {

    private WebDriver driver;

    private Map<String, Object> vars;

    private JavascriptExecutor js;

    @Before
    public void setUp() {
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
        driver.get("http://localhost:8080/administrator/");
        driver.manage().window().setSize(new Dimension(1280, 720));
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    /* 
     * NOTE: the tests numbers are in index-1 with respect to the cases in the Gherkin directory
     * This choice has been made to make tests execution in ascending name order 
    */
    @Test
    public void testFeature3() {
        /*
         *  Feature: Localization management
            Scenario: Adds a new state
         */
        new LoginPage(driver, js, vars).adminLogin("admin@prestashop.com", "password");
        DashboardPage _DashboardPage = new DashboardPage(driver, js, vars);
        _DashboardPage.ClickLocalization();
        StatesPage _StatesPage = new StatesPage(driver, js, vars);
        _StatesPage.addState();
        AddNewStatePage _AddNewStatePage = new AddNewStatePage(driver, js, vars);
        _AddNewStatePage.addDetails("Liguria", "1121", "Europe");
        assert (_StatesPage.verifyStatesAdditionSuccess().size() > 0);
        ProductsPage _ProductsPage = new ProductsPage(driver, js, vars);
        _ProductsPage.logOut();
    }

    @Test
    public void testFeature4() {
        /*
         *  Feature: Localization management
            Scenario: Tries to add an empty state and fails
         */
        new LoginPage(driver, js, vars).adminLogin("admin@prestashop.com", "password");
        DashboardPage _DashboardPage = new DashboardPage(driver, js, vars);
        _DashboardPage.ClickLocalization();
        StatesPage _StatesPage = new StatesPage(driver, js, vars);
        _StatesPage.addState_1();
        AddNewStatePage _AddNewStatePage = new AddNewStatePage(driver, js, vars);
        _AddNewStatePage.verifyRedBox();
        assertThat(_AddNewStatePage.set_CSSSELECTOR_ollinth_child1_1(), is("The iso_code field is required."));
        assertThat(_AddNewStatePage.set_CSSSELECTOR_ollinth_child2(), is("The name field is required."));
        ProductsPage _ProductsPage = new ProductsPage(driver, js, vars);
        _ProductsPage.logOut();
    }

}
