package TestCases;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.FixMethodOrder;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;
import TestCases.PO.*;
import org.junit.runners.MethodSorters;

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class ProductTestCases {

    private WebDriver driver;

    private Map<String, Object> vars;

    private JavascriptExecutor js;

    @Before
    public void setUp() {
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
        driver.get("http://localhost:8080/administrator/");
        driver.manage().window().setSize(new Dimension(1280, 720));
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void testFeature0() {
        /*
         *  Feature: Catalog management
            Scenario: Adds a new product
         */
        new LoginPage(driver, js, vars).adminLogin("admin@prestashop.com", "password");
        DashboardPage _DashboardPage = new DashboardPage(driver, js, vars);
        _DashboardPage.ClickCatalog();
        ProductsPage _ProductsPage = new ProductsPage(driver, js, vars);
        _ProductsPage.addProduct();
        AddProductPage _AddProductPage = new AddProductPage(driver, js, vars);
        _AddProductPage.setProductName("Blue Jacket3");
        assert (_ProductsPage.verifyAddingProductSuccessfully().size() > 0);
        _ProductsPage.logOut();
    }

    @Test
    public void testFeature1() {
        /*
         *  Feature: Catalog management
            Scenario: Tries to add a product without name and fails
         */
        new LoginPage(driver, js, vars).adminLogin("admin@prestashop.com", "password");
        DashboardPage _DashboardPage = new DashboardPage(driver, js, vars);
        _DashboardPage.ClickCatalog();
        ProductsPage _ProductsPage = new ProductsPage(driver, js, vars);
        _ProductsPage.addProduct_1();
        assertThat(_ProductsPage.set_CSSSELECTOR_ollinth_child1(), is("This link_rewrite field is required at least in English (English)"));
        assertThat(_ProductsPage.set_CSSSELECTOR_ollinth_child2(), is("This name field is required at least in English (English)"));
        _ProductsPage.logOut();
    }

    @Test
    public void testFeature2() {
        /*
         *  Feature: Catalog management
            Scenario: Changes the name of a product
         */
        new LoginPage(driver, js, vars).adminLogin("admin@prestashop.com", "password");
        DashboardPage _DashboardPage = new DashboardPage(driver, js, vars);
        _DashboardPage.ClickCatalog_1();
        EditProductPage _EditProductPage = new EditProductPage(driver, js, vars);
        _EditProductPage.changeProductName("Deep Blue Jacket");
        ProductsPage _ProductsPage = new ProductsPage(driver, js, vars);
        assert (_ProductsPage.verifyAddingProductSuccessfully().size() > 0);
        _ProductsPage.logOut();
    }

    @Test
    public void testFeature5() {
        /*
         *  Feature: Catalog management
            Scenario: Checks that taxes are computed correctly when adding a new product
         */
        new LoginPage(driver, js, vars).adminLogin("admin@prestashop.com", "password");
        DashboardPage _DashboardPage = new DashboardPage(driver, js, vars);
        _DashboardPage.ClickCatalog();
        ProductsPage _ProductsPage = new ProductsPage(driver, js, vars);
        _ProductsPage.click_ID_page_header_desc_product_new_product();
        AddNewStatePage _AddNewStatePage = new AddNewStatePage(driver, js, vars);
        _AddNewStatePage.selectPrices();
        AddProductPage _AddProductPage = new AddProductPage(driver, js, vars);
        _AddProductPage.setPreTaxRetailPrice("10");
        assertThat(_AddProductPage.set_ID_priceTI(), is("12.20"));
        _ProductsPage.logOut();
    }

    @Test
    public void testFeature6() {
        /*
         *  Feature: Catalog management
            Scenario: Checks that taxes are computed correctly when adding a new product using the italian reduced VAT rate (10%)
        */
        new LoginPage(driver, js, vars).adminLogin("admin@prestashop.com", "password");
        DashboardPage _DashboardPage = new DashboardPage(driver, js, vars);
        _DashboardPage.ClickCatalog();
        ProductsPage _ProductsPage = new ProductsPage(driver, js, vars);
        _ProductsPage.click_ID_page_header_desc_product_new_product();
        AddNewStatePage _AddNewStatePage = new AddNewStatePage(driver, js, vars);
        _AddNewStatePage.selectPrices();
        AddProductPage _AddProductPage = new AddProductPage(driver, js, vars);
        _AddProductPage.setPreTaxRetailPrice_1("10", "IT Reduced Rate (10%)");
        assertThat(_AddProductPage.set_ID_priceTI(), is("11.00"));
        _ProductsPage.logOut();
    }

    @Test
    public void testFeature7() {
        /*
         *  Feature: Catalog management
            Scenario: Adds a new product feature
         */
        new LoginPage(driver, js, vars).adminLogin("admin@prestashop.com", "password");
        DashboardPage _DashboardPage = new DashboardPage(driver, js, vars);
        _DashboardPage.ClickCatalog_2();
        ProductFeaturesPage _ProductFeaturesPage = new ProductFeaturesPage(driver, js, vars);
        _ProductFeaturesPage.addFeature();
        AddNewFeaturePage _AddNewFeaturePage = new AddNewFeaturePage(driver, js, vars);
        _AddNewFeaturePage.setFeatureName("Strong");
        assert (_ProductFeaturesPage.verifySuccessfulCreation().size() > 0);
        ProductsFeaturesPage _ProductsFeaturesPage = new ProductsFeaturesPage(driver, js, vars);
        _ProductsFeaturesPage.logOut();
    }

    @Test
    public void testFeature8() {
        /*
         *  Feature: Catalog management
            Scenario: Tries to add a feature without name and fails
         */
        new LoginPage(driver, js, vars).adminLogin("admin@prestashop.com", "password");
        DashboardPage _DashboardPage = new DashboardPage(driver, js, vars);
        _DashboardPage.ClickCatalog_2();
        ProductFeaturesPage _ProductFeaturesPage = new ProductFeaturesPage(driver, js, vars);
        _ProductFeaturesPage.addFeature_1();
        assert (_ProductFeaturesPage.set_CSSSELECTOR_alert_danger().size() > 0);
        _ProductFeaturesPage.logOut();
    }

    @Test
    public void testFeature9() {
        /*
         *  Feature: Catalog management
            Scenario: Adds a new product attribute
         */
        new LoginPage(driver, js, vars).adminLogin("admin@prestashop.com", "password");
        DashboardPage _DashboardPage = new DashboardPage(driver, js, vars);
        _DashboardPage.ClickCatalog_3();
        ProductAttributesPage _ProductAttributesPage = new ProductAttributesPage(driver, js, vars);
        _ProductAttributesPage.addNewAttribute();
        AddNewAttributePage _AddNewAttributePage = new AddNewAttributePage(driver, js, vars);
        _AddNewAttributePage.addAttributeDetails("Quantity", "Qnt");
        assert (_ProductAttributesPage.verifySuccessfulCreation().size() > 0);
        ProductsPage _ProductsPage = new ProductsPage(driver, js, vars);
        _ProductsPage.logOut();
    }
}
