package TestCases.PO;

// Generated by Selenium IDE
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;

public class AddProductPage {

    WebDriver driver;

    JavascriptExecutor js;

    Map<String, Object> vars;

    public AddProductPage(WebDriver driver, JavascriptExecutor js, Map<String, Object> vars) {
        this.driver = driver;
        this.js = js;
        this.vars = vars;
    }

    public void set_ID_name_1(String key1) {
        By elem = By.id("name_1");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
        driver.findElement(elem).clear();
        driver.findElement(elem).sendKeys(key1);
    }

    public void click_CSSSELECTOR_panel_footernth_child22btnnth_child2process_icon_save() {
        By elem = By.cssSelector(".panel-footer:nth-child(22) > .btn:nth-child(2) > .process-icon-save");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void setProductName(String key1) {
        set_ID_name_1(key1);
        click_CSSSELECTOR_panel_footernth_child22btnnth_child2process_icon_save();
    }

    public void checkRetailPriceWithTax(String key1) {
        By elem = By.id("priceTI");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void setPreTaxRetailPrice(String key1) {
        By elem = By.id("priceTE");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
        driver.findElement(elem).clear();
        driver.findElement(elem).sendKeys(key1);
        checkRetailPriceWithTax(key1);
    }

    public String set_ID_priceTI() {
        By elem = By.id("priceTI");
        MyUtils.WaitForElementLoaded(driver, elem);
        String value = driver.findElement(elem).getAttribute("value");
        return value;
    }

    public void setITReducedRate(String key1, String key2) {
        By elem = By.id("id_tax_rules_group");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
        {
            WebElement dropdown = driver.findElement(elem);
            elem = By.cssSelector("option:nth-child(5)");
            MyUtils.WaitForElementLoaded(driver, elem);
            dropdown.findElement(elem).click();
        }
    }

    public void setPreTaxRetailPrice_1(String key1, String key2) {
        By elem = By.id("priceTE");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
        driver.findElement(elem).clear();
        driver.findElement(elem).sendKeys(key1);
        setITReducedRate(key1, key2);
    }
}
