package TestCases.PO;

// Generated by Selenium IDE
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;

public class EditProductPage {

    WebDriver driver;

    JavascriptExecutor js;

    Map<String, Object> vars;

    public EditProductPage(WebDriver driver, JavascriptExecutor js, Map<String, Object> vars) {
        this.driver = driver;
        this.js = js;
        this.vars = vars;
    }

    public void set_ID_name_1(String key1) {
        By elem = By.id("name_1");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
        driver.findElement(elem).clear();
        driver.findElement(elem).sendKeys(key1);
        js.executeScript("window.scrollTo(0,835)");
    }

    public void click_CSSSELECTOR_panel_footernth_child22btnnth_child2process_icon_save() {
        By elem = By.cssSelector(".panel-footer:nth-child(22) > .btn:nth-child(2) > .process-icon-save");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void changeProductName(String key1) {
        set_ID_name_1(key1);
        click_CSSSELECTOR_panel_footernth_child22btnnth_child2process_icon_save();
    }
}
