package TestCases.PO;

// Generated by Selenium IDE
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;

public class LoginPage {

    WebDriver driver;

    JavascriptExecutor js;

    Map<String, Object> vars;

    public LoginPage(WebDriver driver, JavascriptExecutor js, Map<String, Object> vars) {
        this.driver = driver;
        this.js = js;
        this.vars = vars;
    }

    public void set_ID_email(String key1) {
        By elem = By.id("email");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
        driver.findElement(elem).clear();
        driver.findElement(elem).sendKeys(key1);
    }

    public void set_ID_passwd(String key2) {
        By elem = By.id("passwd");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
        driver.findElement(elem).clear();
        driver.findElement(elem).sendKeys(key2);
    }

    public void click_NAME_submitLogin() {
        By elem = By.name("submitLogin");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void adminLogin(String key1, String key2) {
        set_ID_email(key1);
        set_ID_passwd(key2);
        click_NAME_submitLogin();
    }
}
