package TestCases.PO;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class DashboardPage {

    WebDriver driver;

    JavascriptExecutor js;

    Map<String, Object> vars;

    public DashboardPage(WebDriver driver, JavascriptExecutor js, Map<String, Object> vars) {
        this.driver = driver;
        this.js = js;
        this.vars = vars;
    }

    public void click_LINKTEXT_States() {
        By elem = By.linkText("States");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void ClickLocalization() {
        {
            By elem = By.cssSelector("#maintab-AdminParentLocalization span");
            MyUtils.WaitForElementLoaded(driver, elem);
            WebElement element = driver.findElement(elem);
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        click_LINKTEXT_States();
    }

    public void ClickProducts() {
        By elem = By.linkText("Products");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void ClickCatalog() {
        {
            By elem = By.cssSelector("#maintab-AdminCatalog span");
            MyUtils.WaitForElementLoaded(driver, elem);
            WebElement element = driver.findElement(elem);
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        ClickProducts();
    }

    public void click_CSSSELECTOR_tr__8_0edit() {
        By elem = By.cssSelector("#tr__8_0 .edit");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void ClickCatalog_1() {
        {
            By elem = By.cssSelector("#maintab-AdminCatalog span");
            MyUtils.WaitForElementLoaded(driver, elem);
            WebElement element = driver.findElement(elem);
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        ClickProducts();
        click_CSSSELECTOR_tr__8_0edit();
    }

    public void ClickProductFeatures() {
        By elem = By.linkText("Product Features");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void ClickCatalog_2() {
        {
            By elem = By.cssSelector("#maintab-AdminCatalog span");
            MyUtils.WaitForElementLoaded(driver, elem);
            WebElement element = driver.findElement(elem);
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        ClickProductFeatures();
    }

    public void ClickProductAttributes() {
        By elem = By.linkText("Product Attributes");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void ClickCatalog_3() {
        {
            By elem = By.cssSelector("#maintab-AdminCatalog span");
            MyUtils.WaitForElementLoaded(driver, elem);
            WebElement element = driver.findElement(elem);
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        ClickProductAttributes();
    }
}
