// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ContentTestSuiteTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testFeature1() {
    driver.get("http://localhost:8080/admin");
    driver.manage().window().setSize(new Dimension(1280, 720));
    System.out.println("{ASSESSOR}:LoginPage:adminLogin");
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("admin");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("password");
    driver.findElement(By.cssSelector(".uk-button")).click();
    System.out.println("{ASSESSOR}:MenuPage:selectNewContent");
    driver.findElement(By.linkText("New content")).click();
    System.out.println("{ASSESSOR}:EditNewContentPage:editTitleAndSave");
    driver.findElement(By.id("jstitle")).click();
    driver.findElement(By.id("jstitle")).sendKeys("Test Content");
    driver.findElement(By.cssSelector(".uk-button:nth-child(1)")).click();
    System.out.println("{ASSESSOR}:ManageContentPage:testNewContentAddedSuccessfully");
    {
      List<WebElement> elements = driver.findElements(By.linkText("Test Content"));
      assert(elements.size() > 0);
    }
    {
      WebDriverWait wait = new WebDriverWait(driver, 5);
      wait.until(ExpectedConditions.invisibilityOfElementLocated(By.id("alert")));
    }
    System.out.println("{ASSESSOR}:ManageContentPage:logOut");
    driver.findElement(By.linkText("Log out")).click();
  }
  @Test
  public void testFeature2() {
    driver.get("http://localhost:8080/admin");
    driver.manage().window().setSize(new Dimension(1280, 720));
    System.out.println("{ASSESSOR}:LoginPage:adminLogin");
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("admin");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("password");
    driver.findElement(By.cssSelector(".uk-button")).click();
    System.out.println("{ASSESSOR}:MenuPage:selectContent");
    driver.findElement(By.linkText("Content")).click();
    driver.findElement(By.linkText("Test Content")).click();
    driver.findElement(By.cssSelector("li:nth-child(7) > .sidebar-button")).click();
    driver.findElement(By.id("jsslug")).click();
    System.out.println("{ASSESSOR}:EditContentPage:changeFriendlyUrl");
    driver.findElement(By.id("jsslug")).sendKeys("new-post-url");
    driver.findElement(By.cssSelector(".uk-button:nth-child(1)")).click();
    driver.findElement(By.linkText("Content")).click();
    System.out.println("{ASSESSOR}:ManageContentPage:assertUrlChangedSuccessfully");
    assertThat(driver.findElement(By.linkText("/new-post-url")).getText(), is("/new-post-url"));
    System.out.println("{ASSESSOR}:ManageContentPage:logOut");
    driver.findElement(By.linkText("Log out")).click();
  }
  @Test
  public void testFeature3() {
    driver.get("http://localhost:8080/admin");
    driver.manage().window().setSize(new Dimension(1280, 720));
    System.out.println("{ASSESSOR}:LoginPage:adminLogin");
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("admin");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("password");
    driver.findElement(By.cssSelector(".uk-button")).click();
    System.out.println("{ASSESSOR}:MenuPage:selectContent");
    driver.findElement(By.linkText("Content")).click();
    driver.findElement(By.linkText("Test Content")).click();
    driver.findElement(By.cssSelector("li:nth-child(7) > .sidebar-button")).click();
    driver.findElement(By.cssSelector(".bl-publish-view")).click();
    System.out.println("{ASSESSOR}:EditContentPage:changePosition");
    driver.findElement(By.id("jsposition")).click();
    driver.findElement(By.id("jsposition")).sendKeys("30");
    driver.findElement(By.cssSelector(".uk-button:nth-child(1)")).click();
    driver.findElement(By.linkText("Content")).click();
    System.out.println("{ASSESSOR}:ManageContentPage:selectPublishedContent");
    driver.findElement(By.linkText("Test Content")).click();
    System.out.println("{ASSESSOR}:EditContentPage:testPositionChanged");
    driver.findElement(By.cssSelector(".CodeMirror-scroll")).click();
    driver.findElement(By.cssSelector("li:nth-child(7) > .sidebar-button")).click();
    {
      String value = driver.findElement(By.id("jsposition")).getAttribute("value");
      assertThat(value, is("30"));
    }
    System.out.println("{ASSESSOR}:EditContentPage:logOut");
    driver.findElement(By.linkText("Log out")).click();
  }
  @Test
  public void testFeature4() {
    driver.get("http://localhost:8080/admin");
    driver.manage().window().setSize(new Dimension(1280, 720));
    System.out.println("{ASSESSOR}:LoginPage:adminLogin");
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("admin");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("password");
    driver.findElement(By.cssSelector(".uk-button")).click();
    System.out.println("{ASSESSOR}:MenuPage:selectContent");
    driver.findElement(By.linkText("Content")).click();
    System.out.println("{ASSESSOR}:ManageContentPage:selectPublishedContent");
    driver.findElement(By.linkText("Test Content")).click();
    System.out.println("{ASSESSOR}:EditContentPage:setParent");
    driver.findElement(By.cssSelector("li:nth-child(7) > .sidebar-button")).click();
    driver.findElement(By.id("jsparent")).click();
    {
      WebElement dropdown = driver.findElement(By.id("jsparent"));
      dropdown.findElement(By.xpath("//option[. = 'Create your own content']")).click();
    }
    driver.findElement(By.cssSelector(".uk-button:nth-child(1)")).click();
    System.out.println("{ASSESSOR}:EditContentPage:selectContent");
    driver.findElement(By.linkText("Content")).click();
    driver.findElement(By.linkText("Test Content")).click();
    System.out.println("{ASSESSOR}:EditContentPage:testParentsetSuccessfully");
    driver.findElement(By.cssSelector("li:nth-child(7) > .sidebar-button")).click();
    {
      String value = driver.findElement(By.id("jsparent")).getAttribute("value");
      assertThat(value, is("create-your-own-content"));
    }
    driver.findElement(By.id("jsparent")).click();
    System.out.println("{ASSESSOR}:EditContentPage:logOut");
    driver.findElement(By.linkText("Log out")).click();
  }
  @Test
  public void testFeature5() {
    driver.get("http://localhost:8080/admin");
    driver.manage().window().setSize(new Dimension(1280, 720));
    System.out.println("{ASSESSOR}:LoginPage:adminLogin");
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("admin");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("password");
    driver.findElement(By.cssSelector(".uk-button")).click();
    System.out.println("{ASSESSOR}:MenuPage:selectNewContent");
    driver.findElement(By.cssSelector(".uk-row-first > .uk-panel:nth-child(1) a")).click();
    System.out.println("{ASSESSOR}:EditNewContentPage:editTitleAndSaveDraft");
    driver.findElement(By.id("jstitle")).click();
    driver.findElement(By.id("jstitle")).sendKeys("Draft Content");
    driver.findElement(By.id("jsSaveDraft")).click();
    System.out.println("{ASSESSOR}:ManageContentPage:testDraftAddedSuccessfully");
    {
      List<WebElement> elements = driver.findElements(By.linkText("Draft Content"));
      assert(elements.size() > 0);
    }
    {
      WebDriverWait wait = new WebDriverWait(driver, 5);
      wait.until(ExpectedConditions.invisibilityOfElementLocated(By.id("alert")));
    }
    System.out.println("{ASSESSOR}:ManageContentPage:logOut");
    driver.findElement(By.linkText("Log out")).click();
  }
  @Test
  public void testFeature6() {
    driver.get("http://localhost:8080/admin");
    driver.manage().window().setSize(new Dimension(1280, 720));
    System.out.println("{ASSESSOR}:LoginPage:adminLogin");
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("admin");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("password");
    driver.findElement(By.cssSelector(".uk-button")).click();
    System.out.println("{ASSESSOR}:MenuPage:selectContent");
    driver.findElement(By.linkText("Content")).click();
    System.out.println("{ASSESSOR}:ManageContentPage:selectSetupNewSite");
    driver.findElement(By.linkText("Set up your new site")).click();
    System.out.println("{ASSESSOR}:EditContentPage:setStickyStatus");
    driver.findElement(By.cssSelector("li:nth-child(7) > .sidebar-button")).click();
    driver.findElement(By.id("jsstatus")).click();
    {
      WebElement dropdown = driver.findElement(By.id("jsstatus"));
      dropdown.findElement(By.xpath("//option[. = 'Sticky']")).click();
    }
    driver.findElement(By.cssSelector(".uk-button:nth-child(1)")).click();
    System.out.println("{ASSESSOR}:EditContentPage:selectContent");
    driver.findElement(By.linkText("Content")).click();
    System.out.println("{ASSESSOR}:ManageContentPage:verifyStickyAddedSuccessfully");
    {
      List<WebElement> elements = driver.findElements(By.linkText("Set up your new site"));
      assert(elements.size() > 0);
    }
    System.out.println("{ASSESSOR}:ManageContentPage:logOut");
    driver.findElement(By.linkText("Log out")).click();
  }
  @Test
  public void testFeature7() {
    driver.get("http://localhost:8080/admin");
    driver.manage().window().setSize(new Dimension(1280, 720));
    System.out.println("{ASSESSOR}:LoginPage:adminLogin");
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("admin");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("password");
    driver.findElement(By.cssSelector(".uk-button")).click();
    System.out.println("{ASSESSOR}:MenuPage:selectContent");
    driver.findElement(By.linkText("Content")).click();
    System.out.println("{ASSESSOR}:ManageContentPage:selectFollowBludit");
    driver.findElement(By.linkText("Follow Bludit")).click();
    System.out.println("{ASSESSOR}:EditContentPage:deleteContent");
    driver.findElement(By.id("jsdelete")).click();
    driver.switchTo().alert().accept();
    {
      List<WebElement> elements = driver.findElements(By.linkText("Follow Bludit"));
      assert(elements.size() == 0);
    }
    {
      WebDriverWait wait = new WebDriverWait(driver, 5);
      wait.until(ExpectedConditions.invisibilityOfElementLocated(By.id("alert")));
    }
    System.out.println("{ASSESSOR}:ManageContentPage:logOut");
    driver.findElement(By.linkText("Log out")).click();
  }
}
