// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class UsersTestSuiteTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testFeature8() {
    driver.get("http://localhost:8080/admin");
    driver.manage().window().setSize(new Dimension(1280, 720));
    System.out.println("{ASSESSOR}:LoginPage:adminLogin");
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("admin");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("password");
    driver.findElement(By.cssSelector(".uk-button")).click();
    System.out.println("{ASSESSOR}:MenuPage:selectUsers");
    driver.findElement(By.linkText("Users")).click();
    System.out.println("{ASSESSOR}:UsersPage:addUser");
    driver.findElement(By.linkText("Add a new user")).click();
    System.out.println("{ASSESSOR}:AddUserPage:addUserDetails");
    driver.findElement(By.id("jsnew_username")).click();
    driver.findElement(By.id("jsnew_username")).sendKeys("usertest");
    driver.findElement(By.id("jsnew_password")).click();
    driver.findElement(By.id("jsnew_password")).sendKeys("usertest123");
    driver.findElement(By.id("jsconfirm_password")).click();
    driver.findElement(By.id("jsconfirm_password")).sendKeys("usertest123");
    driver.findElement(By.id("jsemail")).click();
    driver.findElement(By.id("jsemail")).sendKeys("user@test.com");
    driver.findElement(By.id("jsrole")).click();
    {
      WebElement dropdown = driver.findElement(By.id("jsrole"));
      dropdown.findElement(By.xpath("//option[. = 'Administrator']")).click();
    }
    driver.findElement(By.cssSelector(".uk-button-primary")).click();
    System.out.println("{ASSESSOR}:UsersPage:verifyAddedUserSuccessfully");
    {
      List<WebElement> elements = driver.findElements(By.linkText("usertest"));
      assert(elements.size() > 0);
    }
    System.out.println("{ASSESSOR}:UsersPage:logOut");
    driver.findElement(By.linkText("Log out")).click();
  }
  @Test
  public void testFeature9() {
    driver.get("http://localhost:8080/admin");
    driver.manage().window().setSize(new Dimension(1280, 720));
    System.out.println("{ASSESSOR}:LoginPage:adminLogin");
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("admin");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("password");
    driver.findElement(By.cssSelector(".uk-button")).click();
    System.out.println("{ASSESSOR}:MenuPage:selectUsers");
    driver.findElement(By.linkText("Users")).click();
    System.out.println("{ASSESSOR}:UsersPage:selectSecondUser");
    driver.findElement(By.linkText("usertest")).click();
    System.out.println("{ASSESSOR}:EditUserDetailsPage:clickChangePassword");
    driver.findElement(By.linkText("Change password")).click();
    System.out.println("{ASSESSOR}:ChangePasswordPage:changePasswordAndSave");
    driver.findElement(By.id("jsnew_password")).click();
    driver.findElement(By.id("jsnew_password")).sendKeys("newpassword");
    driver.findElement(By.id("jsconfirm_password")).click();
    driver.findElement(By.id("jsconfirm_password")).sendKeys("newpassword");
    driver.findElement(By.cssSelector(".uk-button-primary")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 5);
      wait.until(ExpectedConditions.invisibilityOfElementLocated(By.id("alert")));
    }
    System.out.println("{ASSESSOR}:UsersPage:logOut");
    driver.findElement(By.linkText("Log out")).click();
  }
  @Test
  public void testFeature10() {
    driver.get("http://localhost:8080/admin");
    driver.manage().window().setSize(new Dimension(1280, 720));
    System.out.println("{ASSESSOR}:LoginPage:adminLogin");
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("admin");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("password");
    driver.findElement(By.cssSelector(".uk-button")).click();
    System.out.println("{ASSESSOR}:MenuPage:selectUsers");
    driver.findElement(By.linkText("Users")).click();
    System.out.println("{ASSESSOR}:UsersPage:selectFirstUser");
    driver.findElement(By.linkText("admin")).click();
    System.out.println("{ASSESSOR}:EditUserDetailsPage:editFacebookAndInstagram");
    driver.findElement(By.id("jsfacebook")).click();
    driver.findElement(By.id("jsfacebook")).sendKeys("https://www.facebook.com/some_fake_user_name_52432562135863\"");
    driver.findElement(By.id("jsinstagram")).click();
    driver.findElement(By.id("jsinstagram")).sendKeys("https://instagram.com/some_fake_user_name_52432562135863\"");
    driver.findElement(By.cssSelector(".uk-button-primary")).click();
    System.out.println("{ASSESSOR}:EditUserDetailsPage:selectUsers");
    driver.findElement(By.linkText("Users")).click();
    System.out.println("{ASSESSOR}:UsersPage:selectFirstUser");
    driver.findElement(By.linkText("admin")).click();
    System.out.println("{ASSESSOR}:EditUserDetailsPage:verifyFacebookAdded");
    driver.findElement(By.id("jsfacebook")).click();
    {
      String value = driver.findElement(By.id("jsfacebook")).getAttribute("value");
      assertThat(value, is("https://www.facebook.com/some_fake_user_name_52432562135863\""));
    }
    System.out.println("{ASSESSOR}:EditUserDetailsPage:verifyInstagramAdded");
    driver.findElement(By.id("jsinstagram")).click();
    {
      String value = driver.findElement(By.id("jsinstagram")).getAttribute("value");
      assertThat(value, is("https://instagram.com/some_fake_user_name_52432562135863\""));
    }
    System.out.println("{ASSESSOR}:EditUserDetailsPage:logOut");
    driver.findElement(By.linkText("Log out")).click();
  }
}
